#+TITLE: Links230410

*NB: See scores in folder scores!*

* J.S. Bach: Messe in h. BWV

** Version 1. Recording by Cantus Cölln (Konrad Junghänel)

Youtube playlist:

https://www.youtube.com/watch?v=KBELAexyILg&list=OLAK5uy_k9jmLBUzGR2Qc76LhcN8-FLPK3589mmFA

Tracks recommended for study:

*** Confiteor https://www.youtube.com/watch?v=JaEg8m-D8Ng&list=OLAK5uy_k9jmLBUzGR2Qc76LhcN8-FLPK3589mmFA&index=20&pp=8AUB
*** Et expecto https://www.youtube.com/watch?v=UQWVNi1VBJI&list=OLAK5uy_k9jmLBUzGR2Qc76LhcN8-FLPK3589mmFA&index=21&pp=8AUB
*** Sanctus https://www.youtube.com/watch?v=SYWHnq8X7rk&list=OLAK5uy_k9jmLBUzGR2Qc76LhcN8-FLPK3589mmFA&index=22&pp=8AUB
*** Agnus Dei https://www.youtube.com/watch?v=12TLSNpGhFk&list=OLAK5uy_k9jmLBUzGR2Qc76LhcN8-FLPK3589mmFA&index=26
*** Dona nobis pacem https://www.youtube.com/watch?v=XbAhklyVmJs&list=OLAK5uy_k9jmLBUzGR2Qc76LhcN8-FLPK3589mmFA&index=27
** Version 2. Recording by Collegium Vocale Gent (Philippe Herreweghe)

https://www.youtube.com/watch?v=TElchGZ1xT0

* J.S. Bach: Johannes Passion
** Version 0. Thomanerchor in the Thomas Kirche Mar 27, 2023

https://www.youtube.com/watch?v=fF0_EPzcE_I

** Version 1: Recording by Cantus Cölln. Direction: Konrad Junghänel.

J. S. Bach- Johannes-Passion BWV 245 (Version IV 1749)- K. Junghänel

https://www.youtube.com/watch?v=0KVcAHXoPDs

*** Part I: Chorale: Herr, unser Herrscher (Chorus)
https://www.youtube.com/watch?v=0KVcAHXoPDs&t=0s

*** Chor. Ruht wohl, ihr heiligen Gebeine
+ 40 Coral. Ach Herr, Laß Dein Lieb Engelein
https://www.youtube.com/watch?v=0KVcAHXoPDs&t=6005s
*** Coral. Er Nahm Alles Wohl29. Recitativo. Und Von Stund An. Aria. Es Ist Vollbracht
https://www.youtube.com/watch?v=0KVcAHXoPDs&t=4469s

Note: Cf sound of Lirone: https://youtu.be/ybig-0BBihA?t=353

** Version 2: Recording by Bach Collegium Japan.  Direction: Masaaki Suzuki (2014)

*** Chorus. "Herr, unser Herrscher". https://www.youtube.com/watch?v=SiKgrevzT-g

*** Es ist vollbracht:
https://youtu.be/SiKgrevzT-g?t=4514

** Version 3: Recording by Bach Collegium Japan. Direction: Masaaki Suzuki (Apr 9, 2020  KÖLNER PHILHARMONIE)

*** Chorus. "Herr, unser Herrscher"
https://www.youtube.com/watch?v=ZKYscw-nN8U

*** Es ist vollbracht:
https://youtu.be/ZKYscw-nN8U?t=4417
** Version 4: Recording by Freiburger Bachchor und Freiburger Bachorchester. Direction: Hannes Reich (Konzerthaus Freiburg | 12.03.2023)

https://www.youtube.com/watch?v=6zTcZaDclHQ
** Version 5: Barrocade Ensemble

https://www.youtube.com/watch?v=sP3vlIPuK0s

The characteristic Viola motiv in the opening Chorus is most audible in this recording.

* J.S. Bach: Matthäuspassion

** Freiburger Barockorchester

https://www.youtube.com/watch?v=3fP-rET0kFI

* J.S. Bach: Orgelbüchlein

Peter Breugelmans plays the complete Orgelbüchlein - Bach Concerts Ghent

https://www.youtube.com/watch?v=hj9bBm6JZ3w

Shows both hands and feet on 2 separate video feeds!

See score PDF in folder Scores.
