#+TITLE: Notes230503_music Rhetoric Cognition Bach

Some references and links:

Dietrich Bartel (1997), Musica Poetica: Musical-Rhetorical Figures in German Baroque Music, Lincoln and London, University of Nebraska Press.

Bach Chaconne: Midori Seiler.
https://www.youtube.com/watch?v=KgSKvOAJMb8

Ζεεβ Στερνχελλ: Αντι-Διαφωτισμός.

Baruch Spinoza :

---
Deleuze:
 - Spinoza
 - Leibnitz
---

Neill Stephenson : The Baroque Cycle
Neill Stephenson : Anathem (The Clock of the Long Now)
Neill Stephenson : *Snowcrash*

---

Recommended starting points for study:

- Orgelbüchlein (BWV 599-644) https://www.youtube.com/watch?v=hj9bBm6JZ3w
- Clavier-Übung III (BWV 552, 669-689, 802-805) https://www.youtube.com/watch?v=CKveVnk-UhM

Recommended blog and videos for inspiration and insight :

Jaremy Denk's https://www.jeremydenk.com/blog
Especially the older entries:
Think Denk: https://blog.jeremydenk.com/

Jeremy Denk's youtube video's on Bach:

(No recommendation on viewing order:)

- The Well-Tempered Clavier’s Greatest Hits with Jeremy Denk https://www.youtube.com/watch?v=7nMPRuvVi20
- NPR: The Goldberg Variations with Jeremy Denk: Variation No. 18 & 25 https://www.youtube.com/watch?v=ZIUbfaAShLg
- NPR: The Goldberg Variations with Jeremy Denk: Variation No. 15 https://www.youtube.com/watch?v=lprNLlPI1FU
- How to Think Like Bach (Denk in dialogue with neuroscientist and cognitive psychologist Daniel Levitin) https://www.youtube.com/watch?v=FyMimOEDuqU

Maybe also:
- The Mysterious Life of J.S. Bach https://www.youtube.com/watch?v=_AGvoVETvd8
