#+TITLE: Notes230315

* Αλέξανδρος Μονοκάνδυλος

Ερωτήματα γενικά.

Quasimodo the great lover
https://greenleafmusic.com/telematic-performance-quasimodo-the-great-lover/
https://mattrogalsky.bandcamp.com/track/quasimodo-the-great-lover-alvin-lucier
http://www.transnationalecologies.net/

** Λύση 1

https://www.sensestage.eu/

** Λύση 2

https://shop.m5stack.com/products/m5stickc-plus-esp32-pico-mini-iot-development-kit

M5stick pro + Router.

* Άγαθα Μίγγου

Πως κάνω έρευνα; Πως βρίσκω θέμα.

* Παρασκευή (Βιβή) Περυσινάκη

* Φανή Αράπη

* Θανάσης Λιακόπουλος

* Κωνσταντίνος Νησίδης

Rudolf Arnheim Εντροπία και Τέχνη

Σεισμοί

Κλιμακα - η εντροπία και το χάος εξαρτώνται από την κλίμακα παρατήρησης.

Το χρονικό του χρόνου
Ψυχολογικό και κοσμικό βέλος του χρόνου
Εμπειρία του χρόνου μέσα από την ύλη

Έλλειψη πανεποπτίας στην εμπειρία του ήχου

Ο σεισμός σαν ξεχωριστό γεγονός και σαν συνεχής καταγραφή.

Προσιτές σεισμογραφικές συσκευές;;;;;;;

* Κατερίνα Δούναβη

* Ιωάννα Τζάμπα

* Ευφροσύνη Καρμανώλη

* Κωνσταντίνα Καϊκα

* Σοφία Ανδρουτσοπούλου

* Φωτεινή Στάχτιαρη

* Σόφη Μουτάφη

* Ελένη Μητρούσκα

* Ρήγας Κούγκολος

* Βασιλική Καλαφάτη

* Αλλες προτάσεις για εργασίες

https://www.youtube.com/watch?v=2TgFp76Rnig
 Mathematics of African Dance Rhythms

 https://www.youtube.com/watch?v=12BUw_STDVc

  Mitali Khargonkar Vinchurkar ( Tribute to ustad Jahangeer Khan Sahab ) #ustadjahangeerkhasahabtabla
